-- ============================================================
-- V1__init_schema.sql
-- Schema initial de gestion-stock-backend (baseline Flyway)
-- Reflete l'etat de la base genere jusqu'ici par Hibernate
-- (spring.jpa.hibernate.ddl-auto: update), augmente des
-- colonnes d'audit JPA (created_at, updated_at, created_by, updated_by)
-- desormais portees par cm.kfokam.stock.common.entity.AbstractEntity.
-- ============================================================

-- ── entreprises ────────────────────────────────────────────
CREATE TABLE entreprises
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(150)  NOT NULL,
    description  VARCHAR(1000),
    rue          VARCHAR(150),
    ville        VARCHAR(100),
    code_postal  VARCHAR(20),
    pays         VARCHAR(100),
    code_fiscal  VARCHAR(30)   NOT NULL,
    photo        VARCHAR(255),
    email        VARCHAR(150)  NOT NULL,
    num_tel      VARCHAR(20),
    site_web     VARCHAR(150),
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP,
    created_by   VARCHAR(255)  NOT NULL,
    updated_by   VARCHAR(255),
    CONSTRAINT uk_entreprises_code_fiscal UNIQUE (code_fiscal),
    CONSTRAINT uk_entreprises_email UNIQUE (email)
);

-- ── utilisateurs ───────────────────────────────────────────
CREATE TABLE utilisateurs
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                   VARCHAR(100)  NOT NULL,
    prenom                VARCHAR(100)  NOT NULL,
    email                 VARCHAR(150)  NOT NULL,
    mot_de_passe          VARCHAR(255)  NOT NULL,
    date_de_naissance     DATE,
    photo                 VARCHAR(255),
    rue                   VARCHAR(150),
    ville                 VARCHAR(100),
    code_postal           VARCHAR(20),
    pays                  VARCHAR(100),
    entreprise_id         BIGINT        NOT NULL,
    must_change_password  BOOLEAN       NOT NULL,
    created_at            TIMESTAMP     NOT NULL,
    updated_at            TIMESTAMP,
    created_by            VARCHAR(255)  NOT NULL,
    updated_by            VARCHAR(255),
    CONSTRAINT uk_utilisateurs_email UNIQUE (email),
    CONSTRAINT fk_utilisateurs_entreprise FOREIGN KEY (entreprise_id) REFERENCES entreprises (id)
);

-- ── utilisateur_roles (table de collection @ElementCollection) ──
CREATE TABLE utilisateur_roles
(
    utilisateur_id BIGINT      NOT NULL,
    role           VARCHAR(20),
    CONSTRAINT fk_utilisateur_roles_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id)
);

-- ── categories ─────────────────────────────────────────────
CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(20)   NOT NULL,
    designation   VARCHAR(255)  NOT NULL,
    entreprise_id BIGINT        NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(255)  NOT NULL,
    updated_by    VARCHAR(255),
    CONSTRAINT uk_categories_code_entreprise UNIQUE (code, entreprise_id),
    CONSTRAINT fk_categories_entreprise FOREIGN KEY (entreprise_id) REFERENCES entreprises (id)
);

-- ── articles ───────────────────────────────────────────────
CREATE TABLE articles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(20)    NOT NULL,
    designation         VARCHAR(255)   NOT NULL,
    prix_unitaire_ht    NUMERIC(12, 2) NOT NULL,
    taux_tva            NUMERIC(5, 2)  NOT NULL,
    prix_unitaire_ttc   NUMERIC(12, 2) NOT NULL,
    photo               VARCHAR(255),
    seuil_minimum       NUMERIC(12, 2) NOT NULL,
    category_id         BIGINT         NOT NULL,
    entreprise_id       BIGINT         NOT NULL,
    created_at          TIMESTAMP      NOT NULL,
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255)   NOT NULL,
    updated_by          VARCHAR(255),
    CONSTRAINT uk_articles_code_entreprise UNIQUE (code, entreprise_id),
    CONSTRAINT fk_articles_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_articles_entreprise FOREIGN KEY (entreprise_id) REFERENCES entreprises (id)
);

-- ── clients ────────────────────────────────────────────────
CREATE TABLE clients
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(100)  NOT NULL,
    prenom        VARCHAR(100)  NOT NULL,
    email         VARCHAR(150)  NOT NULL,
    num_tel       VARCHAR(20),
    rue           VARCHAR(150),
    ville         VARCHAR(100),
    code_postal   VARCHAR(20),
    pays          VARCHAR(100),
    photo         VARCHAR(255),
    entreprise_id BIGINT        NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(255)  NOT NULL,
    updated_by    VARCHAR(255),
    CONSTRAINT uk_clients_email_entreprise UNIQUE (email, entreprise_id),
    CONSTRAINT fk_clients_entreprise FOREIGN KEY (entreprise_id) REFERENCES entreprises (id)
);

-- ── fournisseurs ───────────────────────────────────────────
CREATE TABLE fournisseurs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(100)  NOT NULL,
    prenom        VARCHAR(100)  NOT NULL,
    email         VARCHAR(150)  NOT NULL,
    num_tel       VARCHAR(20),
    rue           VARCHAR(150),
    ville         VARCHAR(100),
    code_postal   VARCHAR(20),
    pays          VARCHAR(100),
    photo         VARCHAR(255),
    entreprise_id BIGINT        NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(255)  NOT NULL,
    updated_by    VARCHAR(255),
    CONSTRAINT uk_fournisseurs_email_entreprise UNIQUE (email, entreprise_id),
    CONSTRAINT fk_fournisseurs_entreprise FOREIGN KEY (entreprise_id) REFERENCES entreprises (id)
);

-- ── commandes_client ───────────────────────────────────────
CREATE TABLE commandes_client
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_commande  VARCHAR(30)    NOT NULL,
    date_commande  DATE           NOT NULL,
    etat_commande  VARCHAR(20)    NOT NULL,
    client_id      BIGINT         NOT NULL,
    total_ht       NUMERIC(14, 2) NOT NULL,
    total_tva      NUMERIC(14, 2) NOT NULL,
    total_ttc      NUMERIC(14, 2) NOT NULL,
    entreprise_id  BIGINT         NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255)   NOT NULL,
    updated_by     VARCHAR(255),
    CONSTRAINT uk_commandes_client_code_entreprise UNIQUE (code_commande, entreprise_id),
    CONSTRAINT fk_commandes_client_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_commandes_client_entreprise FOREIGN KEY (entreprise_id) REFERENCES entreprises (id)
);

-- ── lignes_commande_client ─────────────────────────────────
CREATE TABLE lignes_commande_client
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_client_id  BIGINT         NOT NULL,
    article_id          BIGINT         NOT NULL,
    quantite            INTEGER        NOT NULL,
    prix_unitaire_ht     NUMERIC(12, 2) NOT NULL,
    prix_unitaire_ttc    NUMERIC(12, 2) NOT NULL,
    created_at          TIMESTAMP      NOT NULL,
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255)   NOT NULL,
    updated_by          VARCHAR(255),
    CONSTRAINT fk_lignes_commande_client_commande FOREIGN KEY (commande_client_id) REFERENCES commandes_client (id),
    CONSTRAINT fk_lignes_commande_client_article FOREIGN KEY (article_id) REFERENCES articles (id)
);

-- ── commandes_fournisseur ──────────────────────────────────
CREATE TABLE commandes_fournisseur
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_commande  VARCHAR(30)    NOT NULL,
    date_commande  DATE           NOT NULL,
    etat_commande  VARCHAR(20)    NOT NULL,
    fournisseur_id BIGINT         NOT NULL,
    total_ht       NUMERIC(14, 2) NOT NULL,
    total_tva      NUMERIC(14, 2) NOT NULL,
    total_ttc      NUMERIC(14, 2) NOT NULL,
    entreprise_id  BIGINT         NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255)   NOT NULL,
    updated_by     VARCHAR(255),
    CONSTRAINT uk_commandes_fournisseur_code_entreprise UNIQUE (code_commande, entreprise_id),
    CONSTRAINT fk_commandes_fournisseur_fournisseur FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs (id),
    CONSTRAINT fk_commandes_fournisseur_entreprise FOREIGN KEY (entreprise_id) REFERENCES entreprises (id)
);

-- ── lignes_commande_fournisseur ────────────────────────────
CREATE TABLE lignes_commande_fournisseur
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_fournisseur_id BIGINT         NOT NULL,
    article_id              BIGINT         NOT NULL,
    quantite                INTEGER        NOT NULL,
    prix_unitaire_ht         NUMERIC(12, 2) NOT NULL,
    prix_unitaire_ttc        NUMERIC(12, 2) NOT NULL,
    created_at              TIMESTAMP      NOT NULL,
    updated_at              TIMESTAMP,
    created_by              VARCHAR(255)   NOT NULL,
    updated_by              VARCHAR(255),
    CONSTRAINT fk_lignes_commande_fournisseur_commande FOREIGN KEY (commande_fournisseur_id) REFERENCES commandes_fournisseur (id),
    CONSTRAINT fk_lignes_commande_fournisseur_article FOREIGN KEY (article_id) REFERENCES articles (id)
);

-- ── mouvements_stock ───────────────────────────────────────
CREATE TABLE mouvements_stock
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_mvt       TIMESTAMP      NOT NULL,
    quantite       NUMERIC(14, 2) NOT NULL,
    article_id     BIGINT         NOT NULL,
    type_mvt       VARCHAR(20)    NOT NULL,
    source_mvt     VARCHAR(30)    NOT NULL,
    motif          VARCHAR(255),
    id_entreprise  BIGINT         NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255)   NOT NULL,
    updated_by     VARCHAR(255),
    CONSTRAINT fk_mouvements_stock_article FOREIGN KEY (article_id) REFERENCES articles (id)
);

-- ── ventes ─────────────────────────────────────────────────
CREATE TABLE ventes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(30)   NOT NULL,
    date_vente     TIMESTAMP     NOT NULL,
    commentaire    VARCHAR(500),
    id_entreprise  BIGINT        NOT NULL,
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255)  NOT NULL,
    updated_by     VARCHAR(255),
    CONSTRAINT uk_ventes_code UNIQUE (code)
);

-- ── lignes_vente ───────────────────────────────────────────
CREATE TABLE lignes_vente
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vente_id       BIGINT         NOT NULL,
    article_id     BIGINT         NOT NULL,
    quantite       NUMERIC(12, 2) NOT NULL,
    prix_unitaire  NUMERIC(12, 2) NOT NULL,
    id_entreprise  BIGINT         NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255)   NOT NULL,
    updated_by     VARCHAR(255),
    CONSTRAINT fk_lignes_vente_vente FOREIGN KEY (vente_id) REFERENCES ventes (id),
    CONSTRAINT fk_lignes_vente_article FOREIGN KEY (article_id) REFERENCES articles (id)
);
