-- ============================================================
-- V4__add_password_reset_tokens.sql
-- Table pour le flux de reinitialisation de mot de passe oublie
-- (cm.kfokam.stock.auth.model.PasswordResetToken)
-- ============================================================

CREATE TABLE password_reset_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(255)  NOT NULL,
    utilisateur_id  BIGINT        NOT NULL,
    expiration_date TIMESTAMP     NOT NULL,
    used            BOOLEAN       NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP,
    created_by      VARCHAR(255)  NOT NULL,
    updated_by      VARCHAR(255),
    CONSTRAINT uk_password_reset_tokens_token UNIQUE (token),
    CONSTRAINT fk_password_reset_tokens_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id)
);
